/**
 * Renders every measured document straight from the committed evidence files.
 *
 * Hand-editing measured numbers is how a claim drifts away from the evidence
 * that is supposed to support it. Nothing in docs/evaluation.md or the
 * MEASURED block of README.md is written by hand; both are generated here and
 * regenerated by `npm run docs` after every `npm run evidence`.
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

interface Metrics {
  fraud_recall: number; recall_with_review: number; roc_auc: number; precision: number;
  f1: number; fpr: number; fnr: number; review_rate: number; average_precision: number;
  p50_latency_ms: number; p95_latency_ms: number; n_legit: number; n_fraud: number;
}

const root = process.cwd();
const ev = JSON.parse(readFileSync(path.join(root, "data/evidence/latest.json"), "utf8"));
const bench = JSON.parse(readFileSync(path.join(root, "data/evidence/benchmark.json"), "utf8"));

const pc = (x: number, d = 2) => `${(x * 100).toFixed(d)}%`;
const pts = (x: number, d = 2) => `${x >= 0 ? "+" : "−"}${Math.abs(x * 100).toFixed(d)} pts`;
const n = (x: number) => x.toLocaleString("en-US");

const base: Metrics = ev.baseline;
const before: Metrics = ev.defense_gate.held_out_before;
const after: Metrics = ev.defense_gate.held_out_after;
const sig = ev.defense_gate.significance;
const ci = ev.defense_gate.recall_95ci;
const blind = ev.blind_spot;
const budgets = ev.gate_budgets;
const det = ev.detector;

const METRIC_ROWS: [string, keyof Metrics][] = [
  ["Recall — declined", "fraud_recall"],
  ["Recall — declined or held for review", "recall_with_review"],
  ["Precision (on declines)", "precision"],
  ["F1 (on declines)", "f1"],
  ["ROC-AUC", "roc_auc"],
  ["Average precision", "average_precision"],
  ["False-positive rate", "fpr"],
  ["Review rate", "review_rate"],
];

/* --------------------------------------------------------- headline block */

const headline = `<!-- MEASURED:START — generated by \`npm run docs\`; do not edit by hand -->

Reproduce everything below with \`npm run evidence\`. The committed run records commit
\`${String(ev.commit).slice(0, 12)}\` and the fixed seeds \`train=${ev.seeds.train}\`, \`search=${ev.seeds.search}\`,
\`blue_dev=${ev.seeds.blue_dev}\`, \`final_test=${ev.seeds.final_test}\`.

### The detector on attacks it was trained to catch

${n(base.n_fraud)} fraud transactions against ${n(base.n_legit)} legitimate ones — a ${pc(base.n_fraud / (base.n_fraud + base.n_legit), 2)} fraud rate,
chosen to match reported card-fraud prevalence rather than to flatter the numbers.

| Metric | Value |
|---|---:|
${METRIC_ROWS.map(([l, k]) => `| ${l} | ${pc(base[k])} |`).join("\n")}

Precision and F1 are always computed on the strict **decline** definition, so recall can
never be bought by pushing traffic into the review queue.

### The detector on an attack the red team evolved

The red team found \`${blind.scenario_id}\` at generation ${blind.generation} — a ${String(blind.family).replace(/_/g, " ")} variant
descended from \`${blind.parent_scenario_id}\` that evades ${pc(blind.attack_success_rate)} of its own transactions.
The Referee reproduced that evasion across four fresh seeds before the Blue Team was allowed to see it.

| Metric | Before defense | After defense | Change |
|---|---:|---:|---:|
${METRIC_ROWS.map(([l, k]) => `| ${l} | ${pc(before[k])} | ${pc(after[k])} | ${pts(after[k] - before[k])} |`).join("\n")}

Recall counting review holds rises from **${pc(before.recall_with_review)} to ${pc(after.recall_with_review)}**
for ${pts(after.fpr - before.fpr, 3)} of false positives and ${pts(after.review_rate - before.review_rate)} of extra analyst load.

**This is a paired result, not two independent samples.** Both runs scored the same
transactions, so McNemar's test applies: ${sig.after_only} transactions were newly caught and
${sig.before_only} were newly missed, p ${sig.p_value < 0.001 ? "< 0.001" : `= ${sig.p_value}`}. 95% Wilson intervals on the decline
recall are ${pc(ci.before.low, 1)}–${pc(ci.before.high, 1)} before and ${pc(ci.after.low, 1)}–${pc(ci.after.high, 1)} after.

### Why the defense is a new signal and not a lower threshold

The most important table in this repository is the operating curve of the *unchanged*
detector across the *whole* score range on the discovered attack:

| Threshold | Precision | Recall | F1 | False positives |
|---:|---:|---:|---:|---:|
${(ev.held_out_operating_points_v1 as { threshold: number; precision: number; recall: number; f1: number; false_positives: number }[])
  .filter((p) => p.threshold >= 0.3 && p.threshold <= 0.95 && Math.round(p.threshold * 100) % 10 === 0)
  .map((p) => `| ${p.threshold.toFixed(2)} | ${pc(p.precision)} | ${pc(p.recall)} | ${pc(p.f1)} | ${n(p.false_positives)} |`)
  .join("\n")}

There is no operating point that rescues this attack. Lowering the threshold buys false
positives, not recall. That is the argument for the Arena: a novel attack is not a
calibration problem, it is a **missing feature** problem, and you only find out which
feature is missing by generating the attack first.

### Fresh-seed survival

The gate re-evaluates on five fresh-seed recompiles of the blind-spot genome that the
Blue Team never saw.

| Descendant | Evasion before | Evasion after | Result |
|---|---:|---:|---|
${(ev.defense_gate.survival as { scenario_id: string; base_success: number; cand_success: number }[])
  .map((s) => `| \`${s.scenario_id}\` | ${pc(s.base_success)} | ${pc(s.cand_success)} | ${s.cand_success < s.base_success ? "Improved" : "No change"} |`)
  .join("\n")}

### Acceptance budgets

The Referee accepts or rejects; neither AI votes. Verdict: **${ev.defense_gate.accepted ? "ACCEPTED" : "REJECTED"}**${ev.defense_gate.reasons.length ? ` (${ev.defense_gate.reasons.join("; ")})` : ""}.

| Check | Measured | Budget | Result |
|---|---:|---:|---|
| Threat recall gain | ${pts(after.recall_with_review - before.recall_with_review)} | ≥ ${pts(budgets.min_threat_recall_gain, 0)} | ${after.recall_with_review - before.recall_with_review >= budgets.min_threat_recall_gain ? "PASS" : "FAIL"} |
| False-positive increase, absolute | ${pts(after.fpr - before.fpr, 3)} | ≤ ${pts(budgets.max_fpr_delta_abs, 2)} | ${after.fpr - before.fpr <= budgets.max_fpr_delta_abs ? "PASS" : "FAIL"} |
| False-positive increase, relative | ${((after.fpr - before.fpr) / before.fpr * 100).toFixed(0)}% | ≤ ${(budgets.max_fpr_delta_rel * 100).toFixed(0)}% | ${(after.fpr - before.fpr) / before.fpr <= budgets.max_fpr_delta_rel ? "PASS" : "FAIL"} |
| Extra review-queue load | ${pts(after.review_rate - before.review_rate)} | ≤ ${pts(budgets.max_review_rate_delta, 2)} | ${after.review_rate - before.review_rate <= budgets.max_review_rate_delta ? "PASS" : "FAIL"} |
| Fresh descendants improved | ${(ev.defense_gate.survival as { base_success: number; cand_success: number }[]).filter((s) => s.cand_success < s.base_success).length} of ${ev.defense_gate.survival.length} | ≥ ${(budgets.min_survival_share * 100).toFixed(0)}% | ${(ev.defense_gate.survival as { base_success: number; cand_success: number }[]).filter((s) => s.cand_success < s.base_success).length / ev.defense_gate.survival.length >= budgets.min_survival_share ? "PASS" : "FAIL"} |

A flat one-point false-positive allowance was sized for a detector running near 2.8% FPR.
At ${pc(before.fpr)} it would wave through a five-fold increase, so both an absolute and a
relative ceiling apply, plus a budget on the review queue itself.

### Exact replay

Two replays are reported, and they are **not** interchangeable:

- **Discovery scenario** \`${ev.replay.discovery.scenario_id}\`, seed \`${ev.replay.discovery.seed}\` — the stored genome and
  the stored seed, rescored under both defenses. **${ev.replay.discovery.changed_decisions} decisions changed.** This is the causal
  claim about the very attack that was found.
- **Fresh-seed recompiles** of the same genome — **${ev.replay.fresh_seed.reduce((s: number, r: { changed_decisions: number }) => s + r.changed_decisions, 0)} decisions changed** across ${ev.replay.fresh_seed.length} descendants.
  This is a generalisation check and is never presented as evidence about the stored scenario.

### Detector under the hood

\`${det.version}\` — calibrated rules plus logistic regression over ${det.feature_names.length} behavioural features.

| Feature | Weight |
|---|---:|
${det.feature_names.map((f: string) => `| \`${f}\` | ${det.weights[f].toFixed(3)} |`).join("\n")}

Bias ${det.bias.toFixed(3)}. Block threshold ${det.threshold_block}, review threshold ${det.threshold_review}.

The operating point is swept for maximum F1 at **${pc(det.calibration.deploy_prevalence, 1)} deployment fraud prevalence**
under a ${pc(0.003, 1)} false-positive ceiling. The previous calibration took a fixed 98th
percentile of legitimate scores, which pins the false-positive rate at roughly 2% by
construction and caps precision in the single digits regardless of how well the model
separates the classes.

### Throughput

${bench.results[0].trials} trials per scale on Node.js \`${bench.results[0].node}\`, \`${bench.results[0].platform}\`, single process.

| Transactions | Generation | Feature pass | Scoring | p95 scoring | Peak RSS | Experiment |
|---:|---:|---:|---:|---:|---:|---:|
${bench.results.map((r: Record<string, number>) => `| ${n(r.transactions)} | ${n(r.generation_tx_s)} tx/s | ${n(r.feature_tx_s)} tx/s | ${n(r.scoring_tx_s)} tx/s | ${(r.p95_latency_ms * 1000).toFixed(0)} µs | ${r.memory_rss_mb} MB | ${r.experiment_ms} ms |`).join("\n")}

No network, database, queue or provider latency is included, and no network-scale claim
is made.

<!-- MEASURED:END -->`;

/* ------------------------------------------------------------- write files */

const readme = readFileSync(path.join(root, "README.md"), "utf8");
const startMark = "<!-- MEASURED:START";
const endMark = "<!-- MEASURED:END -->";
const s = readme.indexOf(startMark);
const e = readme.indexOf(endMark);
if (s === -1 || e === -1) {
  throw new Error("README.md is missing the MEASURED:START / MEASURED:END markers");
}
writeFileSync(
  path.join(root, "README.md"),
  readme.slice(0, s) + headline + readme.slice(e + endMark.length)
);

const evaluation = `# Measured evaluation

Every number here is produced by the Referee and read straight out of
\`data/evidence/latest.json\` and \`data/evidence/benchmark.json\`.

**This file is generated.** Run \`npm run evidence && npm run docs\` to regenerate it.
Do not edit the numbers by hand — hand-editing is exactly how a claim drifts away from
the evidence that is supposed to support it.

Generated ${ev.generated_at} from commit \`${String(ev.commit).slice(0, 12)}\`.

## Experiment identity

| Field | Value |
|---|---|
${Object.entries(ev.versions).map(([k, v]) => `| ${k.replace(/_/g, " ")} | \`${v}\` |`).join("\n")}
${Object.entries(ev.seeds).map(([k, v]) => `| ${k} seed | \`${v}\` |`).join("\n")}

## Attack families compiled end to end

${(ev.attack_families as string[]).map((f) => `- \`${f}\``).join("\n")}

## The blind spot

\`\`\`json
${JSON.stringify(blind.genome, null, 2)}
\`\`\`

Discovered at generation ${blind.generation}, seed \`${blind.seed}\`, evading ${pc(blind.attack_success_rate)} of
its transactions with a median risk score of ${blind.risk_median}. The detector's catch
reasons on this scenario were ${(blind.top_reasons as string[]).map((r) => `\`${r}\``).join(", ")} — none of
which describe what the attack actually is, which is the point.

## Blue Team proposal

Source: \`${ev.blue_investigation.source}\`.

> ${ev.blue_investigation.proposal.failure_hypothesis}

Evidence cited (all of it Referee output, none of it self-reported):

${(ev.blue_investigation.proposal.evidence as string[]).map((x) => `- ${x}`).join("\n")}

Proposed configuration: \`${JSON.stringify(ev.blue_investigation.proposal.defense_config)}\`,
confidence ${ev.blue_investigation.proposal.confidence}.

${headline.replace(/<!-- MEASURED:(START|END)[^>]*-->/g, "").replace(/^\n+/, "")}

## Test evidence

Run \`npm run selfcheck\` for the linter, type checker, full test suite and production
build. The suite covers legitimate-traffic robustness, outcome-conditioned mutation and
lineage, schema and boundary rejection, blind-spot confirmation, metric integrity
including tie-aware ROC-AUC and average precision, the paired significance test, the
exact replay, prompt-injection and credential guards, provider timeout and malformed
output handling, and byte-identical reruns from identical seeds.
`;
writeFileSync(path.join(root, "docs/evaluation.md"), evaluation);

console.log("rendered README.md measured block and docs/evaluation.md");
